---
title: Premiers pas avec ton Raspberry Pi Pico W
hero_image: images/banner.png
description: Démarre avec ton Raspberry Pi Pico W
version: 4
listed: true
copyedit: true
last_tested: '2022-06-30'
steps:
  - 
    title: Introduction
  - 
    title: Configurer ton Raspberry Pi Pico W
  - 
    title: Connecter ton Raspberry Pi Pico au WLAN
  - 
    title: Ouvrir un socket
  - 
    title: Créer une page web
  - 
    title: Servir ta page web
  - 
    title: Et ensuite ?
