---
title: Premiers pas avec ton Raspberry Pi Pico W
hero_image: images/banner.png
description: Démarrer avec ton Raspberry Pi Pico W
version: 4
listed: true
copyedit: true
last_tested: '2022-06-30'
steps:
  - 
    title: Introduction
  - 
    title: Configurer ton Raspberry Pi Pico W
  - 
    title: Connecter ton Raspberry Pi Pico à un réseau Wi-Fi
  - 
    title: Ouvrir une prise
  - 
    title: Créer une page web
  - 
    title: Serve your webpage
  - 
    title: Et ensuite ?
